#
#

KDE = ~/.local/share/kservices5/ServiceMenus


help:
	@echo    kde:   copy casaviewer.desktop for dolphin menu
	@echo    Uses   KDE=$(KDE)


kde:
	mkdir -p $(KDE)
	cp casaviewer.desktop $(KDE)
	ls -l $(KDE)
