#


qac0:
	pdflatex memo59.tex
	bibtex memo59
	pdflatex memo59.tex
	@echo xdg-open memo59.pdf

#
qac:
	latex memo59.tex
	latex memo59.tex
	bibtex memo59
	latex memo59.tex
	latex memo59.tex
	dvipdfm memo59

