#! /usr/bin/env python
#
#  Will need:
#
#  conda install astropy
#  

import numpy as np
import astropy.wcs as wcs
import astropy.io.fits as fits
from astropy.modeling.models import Gaussian2D

y, x = np.mgrid[0:512, 0:512]
data = (Gaussian2D(1,    150, 100, 20, 10, theta=0.5)(x,y) +
        Gaussian2D(0.5,  400, 300,  8, 12, theta=1.2)(x,y) +
        Gaussian2D(0.75, 250, 400,  5,  7, theta=0.23)(x,y) +
        Gaussian2D(0.9,  425, 150,  3,  3)(x,y) +
        Gaussian2D(0.6,  200, 225,  3,  3)(x,y))
if False:	
   data += 0.01 * np.random.randn(500, 600)
   cosmic_ray_value = 0.997
   data[100, 300:310] = cosmic_ray_value


import matplotlib.pyplot as plt
plt.imshow(data, origin='lower')
plt.show()

w = wcs.WCS(naxis=4)
w.wcs.crpix = [256.0,256.0,1.0,1.0]
w.wcs.cdelt = np.array([-1/3600.0, 1/3600.0, 1.0e9, 1.0])
w.wcs.crval = [180.0, 40.0, 1.15e11, 1.0 ]
w.wcs.ctype = ["RA---SIN", "DEC--SIN", "FREQ", "STOKES"]
# w.wcs.set_pv([(2, 1, 45.0)])


from astropy.nddata import CCDData
ccd = CCDData(data,
              meta={'object': 'FIELD000'},
              wcs=w,
              unit='Jy/pixel')

ccd.write('field000.fits',overwrite=True)

